//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GORI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Gori22 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gori22() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GORI.Resources.Gori22", typeof(Gori22).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For all types of outdoor wood. e.g. doors, windows, fences, beams, panelling etc..
        /// </summary>
        public static string ApplicationAreas {
            get {
                return ResourceManager.GetString("ApplicationAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GORI 22 is a solvent-based preservative product with insecticide, anti-termite and fungicide properties. GORI 22 is used to preserve and cure by spraying or brushing all types of outdoor attacked wood. Recommended to preserve outdoor wood, and materials derived from wood (doors, windows, fences, beams, panelling, furniture, etc.)..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective treatment against all dry wood boring insects (capricorn, lyctus, woodworm). Contains insecticide and fungicide. High penetration properties. Solvent based..
        /// </summary>
        public static string ProductAdvantages {
            get {
                return ResourceManager.GetString("ProductAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For all types of outdoor wood: structures and panelling, beams, furniture, doors, windows, roofs..
        /// </summary>
        public static string RecommendedFor {
            get {
                return ResourceManager.GetString("RecommendedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply on dry, clean wood free from dust, fats, old paint, etc.
        ///Application: Ready to use (do not dilute). Apply on all sides of the wood, as well as sections and ends..
        /// </summary>
        public static string SubstratePreparation {
            get {
                return ResourceManager.GetString("SubstratePreparation", resourceCulture);
            }
        }
    }
}
