//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GORI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Gori44 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gori44() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GORI.Resources.Gori44", typeof(Gori44).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facades and fascias Beams and panelling Fences and pergolas Frames.
        /// </summary>
        public static string ApplicationAreas {
            get {
                return ResourceManager.GetString("ApplicationAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GORI 44 is a solvent based translucent, matt fi nish wood protection with surface fungicide properties. GORI 44 is based on alkyd resins. GORI 44 penetrates deep into the wood..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protects against surface alteration agents such as surface fungi and blue stain High penetration Water repellent Will not crack or peel of.
        /// </summary>
        public static string ProductAdvantages {
            get {
                return ResourceManager.GetString("ProductAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facades, fascias, pergolas and fences..
        /// </summary>
        public static string RecommendedFor {
            get {
                return ResourceManager.GetString("RecommendedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 x GORI 22 + 2 x GORI 44..
        /// </summary>
        public static string RecommendedSystem {
            get {
                return ResourceManager.GetString("RecommendedSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply on dry, clean wood free from dust, fats, old paint, etc. Apply on all sides of the wood, as well as sections and ends..
        /// </summary>
        public static string SubstratePreparation {
            get {
                return ResourceManager.GetString("SubstratePreparation", resourceCulture);
            }
        }
    }
}
